idf_component_register(
    SRCS
        "main.c"
        "modules/rfid_rc522.c"
        "modules/ir_sensor.c"
        "modules/buzzer.c"
        "tasks/security_task.c"
        "tasks/mqtt_task.c"
    INCLUDE_DIRS
        "."
        "modules"
        "tasks"
        "utils"
    REQUIRES
        esp_wifi
        esp_http_client
        mqtt
        nvs_flash
        mbedtls
        driver
        esp_timer
)
